kotlin.code.style=official
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.native.ignoreDisabledTargets=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
group=org.jetbrains.kotlin
version=0.1.0-SNAPSHOT
kotlin.compiler.plugin.devkit.minCliVersion=2.3.20
kotlin.compiler.plugin.devkit.includeBetaAndRc=LATEST
kotlin.compiler.plugin.devkit.minIdeaVersion=262
kotlin.compiler.plugin.devkit.includeIdeaRc=true
kotlin.compiler.plugin.devkit.includeIdeaEap=true
kotlin.compiler.plugin.devkit.useLatestDev=true
kotlin.compiler.plugin.devkit.companionLibraries=:kotlin-library-api-watchdog-plugin-annotations
kotlin.compiler.plugin.devkit.compilerPlugin=:kotlin-library-api-watchdog-compiler-plugin
