kotlin.code.style=official
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.native.ignoreDisabledTargets=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
group=org.jetbrains.kotlin
version=0.1.0-SNAPSHOT
org.jetbrains.kotlin.compiler.plugin.devkit.companionLibraries=:kotlin-library-api-watchdog-plugin-annotations
org.jetbrains.kotlin.compiler.plugin.devkit.compilerPlugin=:kotlin-library-api-watchdog-compiler-plugin
